carla-simulator/leaderboard

leaderboard/leaderboard_evaluator.py, leaderboard/scenarios/route_scenario.py, leaderboard/scenarios/scenario_manager.py
Fixed end of route message bug detecting timeouts as successes.
Fixed _draw_waypoints_ function (responsible of coloring the route depending on the RoadOptions when debugging). Now it no longer uses the clean route, removing unnecessary loops and fixing bugs related to None RoadOptions being colored as STRAIGHT.
Changed timeout from 10 to 30 to avoid timeout errors when loading new maps.
=> Message fix + debug and timeout minor fixes

leaderboard/scenarios/scenario_manager.py
**Problem:** Fixed bug causing routes to get stuck indefinitely when manually interrupted.
**Solution:** Added a CarlaActorPool cleanup when manually interrupting the routes (It was most likely there but was removed by mistake)
=> Fixed bug with manual interrupt

leaderboard/utils/statistics_manager.py
_route_length_kms_ (distance traveled by the agent) now has a minimum of 0.001 to avoid ZeroDivisionError.
=> Fixed bug causing ZeroDivisisonError

leaderboard/autoagents/agent_wrapper.py, leaderboard/autoagents/autonomous_agent.py, leaderboard/autoagents/dummy_agent.py
When I run the example.
`python3 leaderboard/leaderboard_evaluator.py  -a leaderboard/autoagents/dummy_agent.py --scenarios data/all_towns_traffic_scenarios_public.json  --routes data/routes_training.xml --track MAP`
I get the following error.
`Illegal sensor used for Track [Track.SENSORS]!
`
I saw some problems.
* The enum was expect ints not strings
* The agent track was being compared with itself not with the scenario track
* The dummy agent had a wrong track associated.
Here is the PR solving those issues.
=>  fixing the track selection

leaderboard/leaderboard_evaluator.py, leaderboard/scenarios/route_scenario.py, leaderboard/scenarios/scenario_manager.py, leaderboard/utils/route_parser.py
Timeout changes:
- Increased **client timeout** from 30s to **60s**
- Increased **agent blocked** criteria timeout from 90s to **180s**
- Increased the amount of **time given per meter** from 0.4s/m to **0.8s/m**
- Increased the ***world.tick()* timeout** from a fixed 10s to match the client timeout (**60s**)
- Increased the **watchdog timeout** from 5s (last PR), to be a little lower than the client timeout (**58s**). It has to be lower and not equal to ensure it gets triggered before the simulation ends, stopping the scenario
Other changes:
- Moved the recorder after the registering of the statistics, to ensure they are printed (the recorder might get stuck if the simulation crashes)
- Added some clouds to avoid the simulation being too bright
- Removed some unused varaibles at …
=> Increased timeouts

leaderboard/utils/route_indexer.py
The leaderboard crashes if the previous leaderboard run did not complete a route because the progress entry in the json file is an empty list. This PR ensures that the code doesn't directly try to unpack the list, and manually sets the current_route to 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/57)
=> Fixed logic to resume from empty checkpoints.

README.md, requirements.txt
Both carla and srunner have been removed from the requirements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/64)
=> Removed carla and srunner from requirements + README

leaderboard/leaderboard_evaluator.py, leaderboard/scenarios/scenario_manager.py
Fixed bug causing the watchdog to not properly stop the simulation even if there was a timeout during runtime. This was caused by the `_signal_handler()` at *scenario_manager.py* not raising an exception when the watchdog triggered, causing the *leaderboard_evaluator.py* to never stop the simulation.
With the watchdog improvement of [this PR at SR](https://github.com/carla-simulator/scenario_runner/pull/754), two separate watchdogs can be made, one that tracks the simulation, and another one that tracks the agent. A timeout caused by the simulation, as any other error, will stop the LB, correctly saving the statistics. The timeout given by the agent watchdog is treated as any other error coming from the agent, stopping the route and moving to the next one. 
**IMPORTANT:** Note that the PR …
=> Added runtime watchdogs

leaderboard/scenarios/route_scenario.py, leaderboard/scenarios/scenario_manager.py
* Avoid unncessary RPC calls to get the spectator on every tick.
* Make `background_amount` variable accessible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/90)
=> Minor performance improvements

data/new_route_mode.xml, leaderboard/leaderboard_evaluator.py, leaderboard/scenarios/route_scenario.py, leaderboard/utils/route_indexer.py, leaderboard/utils/route_parser.py, scripts/manage_scenarios.py, scripts/run_evaluation.sh
The route parsing has been changed, improving readibility and functionalities.
Routes no longer need to be accompanied by a scenario file. Instead, they are now included as part of the route xml, at the `scenarios` section. While this adds a bit more of work creating the routes, this improves customization by a lot, as two routes that pass through the same point might trigger two complete different scenarios.
As such, the scenario configurations are now *.xml*, and work very similarly to the standalone configuration ones at ScenarioRunner. Its variations come from removing conflicting values such as *weather*, *town*, and *ego_vehicle* is now replaced by *trigger_point*.
An example of a new route would be somethign like this
Additonally, routes now treat imports the same way as the …
=> New route format

data/new_routes_training.xml, leaderboard/utils/statistics_manager.py
Some of the new scenario had an infinite behavior (such as actor flows) or could block the ego forever (with obstacles such as an accident). These scenarios now have a timeout that will stop the scenario, allowing the ego to continue, but will penalise the stack, reducing its score.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/122)
=> Added scenario timeouts

leaderboard/leaderboard_evaluator.py, leaderboard/scenarios/route_scenario.py, leaderboard/scenarios/scenario_manager.py, leaderboard/utils/statistics_manager.py, scripts/run_evaluation.sh
This PR adds the possibility to visualize the statistics of the route while the stack is running.
This is the information provided:
```
Route id: ...
Scores:
Driving score: ...
Route completion: ...
Infraction penalty: ...
Meta:
Route length: ....
Game duration: ...
System duration: ...
Total infractions: ...
Last infractions: (shows the last 5 infractions)
....
```
Live results are enable when the `debug` argument is `>=1`. Live results are provided in a file called `live_results.txt`. This file is generated in the `checkpoint` folder indicated when executing the leaderboard.
Users can visualize this file in real time using the `watch` command:
```sh
watch -n 0.5 cat live_results.txt
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Added live statistics

leaderboard/autoagents/autonomous_agent.py, leaderboard/autoagents/ros1_agent.py, leaderboard/autoagents/ros2_agent.py, leaderboard/autoagents/ros_base_agent.py, leaderboard/leaderboard_evaluator.py
This PR fixes the reconnection issues with roslibpy and the ros-bridge server. To avoid the reconnection issue, the ROS bridge server is not closed until the last route has finished (i.e., the ROS bridge server is not restarted between routes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/127)
=> Fixed ROS1 reconnection issues

data/new_routes_training.xml, leaderboard/leaderboard_evaluator.py, leaderboard/scenarios/route_scenario.py, leaderboard/scenarios/scenario_manager.py, leaderboard/utils/result_writer.py, leaderboard/utils/statistics_manager.py, scripts/merge_statistics.py, scripts/scenario_creator.py
Added the new *VehicleTurningRoute* variations to the training routes and adapted to the *YieldToEmergencyTest* criteria changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/130)
=> Added *VehicleTurningRoute* variations

data/new_routes_training.xml, leaderboard/autoagents/agent_wrapper.py, leaderboard/autoagents/autonomous_agent.py, leaderboard/leaderboard_evaluator.py, leaderboard/scenarios/route_scenario.py, leaderboard/utils/statistics_manager.py, scripts/scenario_creator.py
This PR focused on fixing several issues when shutting down the Leaderboard due to an error (either due to the LB itself, CARLA's server, or the agent), as it is of paramount importance that regardless of what happens, the information of the simulation is properly saved.
Some of the bugs found were:
- Watchdog: they weren't properly shutting down the simulation
- Statistics manager: Shutting down mid simulation caused some data to be missing, breaking it
Others:
- Fixed bug causing the leaderboard to crash when the route timeout was triggered
- At roads, increased the distance between points part of the stack planner to 200
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator …
=> Improved Leaderboard shutdown

data/new_routes_training.xml
BlockedIntersection: 55
VehicleTurningRoute: 39
VehicleTurningRoutePedestrian: 40
VehicleTurningRoutePedestrian_1 move to another place
VehicleTurningRoutePedestrian_1 change to BlockedIntersection_2
VehicleTurningRoutePedestrian_3 removed
VehicleTurningRoute_1 to  x="3485.8" y="-220" z="323.5" yaw="269.5”
VehicleTurningRoutePedestrian_3 to BlockedIntersection_3
VehicleTurningRoutePedestrian_1 removed
VehicleTurningRoute_3 to BlockedIntersection_3
VehicleTurningRoute_1 to BlockedIntersection_1
VehicleTurningRoute_2 to BlockedIntersection_2
VehicleTurningRoute_3 removed
VehicleTurningRoute_1 removed
VehicleTurningRoute_3 to BlockedIntersection_3
VehicleTurningRoute_1 to BlockedIntersection_1
VehicleTurningRoute_2 removed
VehicleTurningRoute_4 to BlockedIntersection_4
VehicleTurningRoute_3 …
=> Fix fence-blocking-actor and main-road-crossing issues

leaderboard/scenarios/scenario_manager.py
Fixed an issue where the simulation could potentially block after a crash
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/158)
=> Fixed bug with scenario thread blocks

leaderboard/autoagents/dummy_agent.py
The [DummyAgent](https://github.com/carla-simulator/leaderboard/blob/111a48f9099c08a2f1068ee8aea2ad56ce52ef9d/leaderboard/autoagents/dummy_agent.py#L58) sensors does not add two keys for the radar sensor, causing an issue later on; [here](https://github.com/carla-simulator/leaderboard/blob/da62c1b75124d6f24b47d4218e0f7169445441ae/leaderboard/autoagents/agent_wrapper.py#L173)
```py
Traceback (most recent call last):
File ".../leaderboard/leaderboard_evaluator.py", line 342, in _load_and_run_scenario
self.manager.load_scenario(self.route_scenario, self.agent_instance, config.index, config.repetition_index)
File ".../leaderboard/leaderboard/scenarios/scenario_manager.py", line 125, in load_scenario
self._agent_wrapper.setup_sensors(self.ego_vehicles[0])
File …
```
=> Fix KeyError when using DummyAgent

leaderboard/autoagents/agent_wrapper.py, leaderboard/envs/sensor_interface.py
This PR removed the special reading frequency of the Opendrive sensor, instead sending it to the agent on each tick, the same as all the other sensors.
Issue #169 highlights one the issues caused by the opendrive having a special reading frequency, and this didn't really make sense in the first place, as sensing the opendrive data each tick doesn't affect performance
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/174)
=> Removed Opendrive reading frequency

leaderboard/leaderboard_evaluator.py
Removes two deprecation warnings that come up in newer python version:
- distutils will be removed in Python3.12, and marked as deprecated in 3.10 [PEP 632](https://peps.python.org/pep-0632/)
- pkg_version, should not be used in newer versions of setuptools https://setuptools.pypa.io/en/latest/pkg_resources.html
This PR can still be used with older Python version that do not provide the new modules.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/172)
=> Remove deprecation warnings for version checking in 3.8 & 3.10+ (2.7 backward compatible)

leaderboard/envs/sensor_interface.py
According to the [sensor reference](https://carla.readthedocs.io/en/latest/ref_sensors/#radar-sensor), data fields of a radar point is `[vel, azimuth, altitude, depth]`. Therefore the output of the callback should be `[depth, altitude, azimuth, vel]` (because of `np.flip`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/180)
=> Fix comment about radar data

leaderboard/utils/route_parser.py
This PR adds the already merged one-line fix from https://github.com/carla-simulator/scenario_runner/pull/1053 
> Replace xml.etree.ElementTree.Element.getchildren method which is deprecated from python 3.2 and removed in python 3.9 with a suggested replacement https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren
```diff
- for elem in scenario.getchildren():
+ for elem in list(scenario):
```
Tested with Python 3.7 and 3.10+; from the deprecation notice should work with 3.2+
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/182)
=> Python 3.9+ support for route_parser; deprecated xml code.
