- leaderboard/scenarios/scenario_manager.py
Reordered the code to add the None checks at the beginning
> Fixed console message bugs

- leaderboard/scenarios/master_scenario.py
- leaderboard/scenarios/scenario_manager.py
- leaderboard/scenarios/scenarioatomics/atomic_criteria.py
- leaderboard/utils/statistics_manager.py
Feature: Add a timeout specific for when the ego-vehicle gets blocked… during more than X seconds.
[Caution] Wait for https://github.com/carla-simulator/scenario_runner/pull/503 to be merged in SR.
> Feature: Add a timeout specific for when the ego-vehicle gets blocked

- leaderboard/leaderboard_evaluator.py
- leaderboard/scenarios/master_scenario.py
- leaderboard/utils/statistics_manager.py
* Statistics now contain information of the the wallclock and simulation times taken by an agent.
> Add: support for time logging as part of the statistics

- leaderboard/leaderboard_evaluator.py
- leaderboard/utils/route_indexer.py
- leaderboard/utils/route_manipulation.py
- leaderboard/utils/route_parser.py
The weather of the routes has been exposed to the user. To change it just add the _weather_ attribute to the .xml file of the route, as a child of the _route_ attribute, along with the parameter values.
E.g:
The default weather is a sunny midday.
**Requires** _Routes now have their weather as a possible parameter #508_ **at ScenarioRunner for this to work**
Additionally, _clean_route_ (at route_manipulation.py) and _run_scenarios_ (at leaderboard_evaluator.py) functions have been removed, as they were unused.
> Routes now have their weather as a possible parameter

- leaderboard/utils/checkpoint_tools.py
- leaderboard/utils/statistics_manager.py
* New naming convention to match the leaderboard UI scheme
> Update: metrics reorganization and naming convention

- leaderboard/autoagents/agent_wrapper.py
- leaderboard/autoagents/dummy_agent.py
- leaderboard/autoagents/human_agent.py
- leaderboard/autoagents/npc_agent.py
- leaderboard/envs/sensor_interface.py
- leaderboard/leaderboard_evaluator.py
- leaderboard/scenarios/scenario_manager.py
- Removed *spectator* and *challenge-mode* arguments, as they were unused.
- Changed LIDAR parsing from 3 to 4 channels to include the new intensity values. Also, changed its range, points per second, and added the new attributes (default values).
- Updated the *sensor* comments at the example agents to avoid confusions, as some were outdated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/53)
> new LIDAR + removal of unused arguments

- leaderboard/leaderboard_evaluator.py
Note: This PR requires scenario_runner:master for it to work. I've exposed the port in the scenario runner as well, but my changes have only been merged into master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/60)
> Expose traffic manager port to enable the simultaneous execution of multiple leaderboards.

- leaderboard/autoagents/agent_wrapper.py
- leaderboard/autoagents/autonomous_agent.py
- leaderboard/autoagents/human_agent.py
- leaderboard/autoagents/human_agent_config.txt
- leaderboard/envs/sensor_interface.py
- leaderboard/leaderboard_evaluator.py
- leaderboard/scenarios/scenario_manager.py
- leaderboard/utils/result_writer.py
- leaderboard/utils/route_indexer.py
- leaderboard/utils/statistics_manager.py
- scripts/run_evaluation.sh
This PR is done in parallel to SR's one (https://github.com/carla-simulator/scenario_runner/pull/629)
Traffic Manager and world
- The **TrafficManager** is now used in **sync mode** and with a fixed seed, which can be chosen through an argument
- Added a traffic light reset after the map is loaded
Agents:
- Added timeout to the agent setup to avoid freezing the simulation indefinitely.
- **Errors during the agent setup no longer stop the simulation, only the route.**
- Changed the structure of the human agent. Instead of running in a parallel thread, it now runs in sync with the rest of the leaderboard. This improves its performance and allows it to be deterministic.
- Increased the human agent camera to 800x600 (from 300x200)
- **Added log and playback to the human agent**. To use them, …
> Several TM and repetition fixes

- README.md
- leaderboard/autoagents/agent_wrapper.py
- leaderboard/autoagents/autonomous_agent.py
- leaderboard/autoagents/human_agent.py
- leaderboard/autoagents/human_agent_config.txt
- leaderboard/envs/sensor_interface.py
- leaderboard/leaderboard_evaluator.py
- leaderboard/scenarios/scenario_manager.py
- leaderboard/utils/result_writer.py
- leaderboard/utils/route_indexer.py
- leaderboard/utils/statistics_manager.py
- requirements.txt
- scripts/run_evaluation.sh
Cherrypicks from master branch to stable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/65)
> Cheerypicks from master

- leaderboard/leaderboard_evaluator.py
- scripts/Dockerfile.master
- scripts/make_docker.sh
* Generic CARLA version in Dockerfile to avoid conflicts with different egg versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/69)
> Generic CARLA version in Dockerfile to avoid conflicts with different egg versions

- leaderboard/leaderboard_evaluator.py
- scripts/Dockerfile.master
- scripts/make_docker.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/72)
> Update stable with latest master

- CHANGELOG.md
- data/routes_training.xml
- leaderboard/envs/sensor_interface.py
- leaderboard/utils/statistics_manager.py
Improvements
- Added a new *scores_std_dev* attribute at the global statistics that computes the std deviation of all the scores. 
- Fixed the global statistics infractions formula:
- It was not taking into account that the *score_route* was a percentage
- Route id 0 of *routes_training.xml* now was its weather displayed to show the users how to easily configure it.
- Removed commented debug prints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/76)
> Added standard deviation to the statistics manager's scores

- CHANGELOG.md
- data/routes_training.xml
- leaderboard/envs/sensor_interface.py
- leaderboard/utils/statistics_manager.py
Improvements
- Added a new scores_std_dev attribute at the global statistics that computes the std deviation of all the scores.
- Fixed the global statistics infractions formula:
- It was not taking into account that the score_route was a percentage
- Route id 0 of routes_training.xml now was its weather displayed to show the users how to easily configure it.
- Removed commented debug prints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/79)
> Added standard deviation to the statistics manager's scores [stable branch]

- leaderboard/autoagents/agent_wrapper.py
- leaderboard/autoagents/autonomous_agent.py
- leaderboard/autoagents/ros_agent.py
- leaderboard/leaderboard_evaluator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/82)
> works with a ros2 stack started with a launchfile

- CHANGELOG.md
- leaderboard/leaderboard_evaluator.py
- scripts/run_evaluation.sh
This PR adds support for the traffic manager hybrid mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/87)
> Add support for traffic manager hybrid mode

- leaderboard/autoagents/ros_base_agent.py
- leaderboard/envs/sensor_interface.py
- leaderboard/leaderboard_evaluator.py
- leaderboard/scenarios/scenario_manager.py
Fixes synchronization issues at the beginning and end of the simulation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/93)
> Fix synchronization ROS agents

- leaderboard/autoagents/npc_agent.py
- leaderboard/leaderboard_evaluator.py
- leaderboard/scenarios/route_scenario.py
- leaderboard/scenarios/scenario_manager.py
- leaderboard/utils/route_manipulation.py
Added compatibility with SR and CARLA 0.9.12, losing compatibility with previous versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/97)
> Added compatibility with CARLA 0.9.12

- leaderboard/leaderboard_evaluator.py
- leaderboard/utils/route_parser.py
- leaderboard/utils/statistics_manager.py
- The check of whether or not a scenario overlaps a route has been changed from a 3D distance check (`sqrt(x^2 + y^2 + z^2) < max_value`) to a 2D distance check along with a max height difference (`sqrt(x^2 + y^2)  < max_value and z < max_value`). This allows a rougher tuning on the z axis, without affecting the x and y one, which is the important part.
- The route length was being computing using the initial waypoints, which could be very far apart. This has been changed to use the more dense trajectory, with points separated every meter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/99)
> Improved several route computations

- leaderboard/leaderboard_evaluator.py
- leaderboard/scenarios/route_scenario.py
- leaderboard/utils/route_parser.py
Improved route configuration parsing. This PR simplifies the code, as it doing an unneeded was parsing the config file into an intermediate format, before parsing again into CARLA classes. Also, scenarios can now have other parameters apart from the ego vehicle, other actors and weather. This PR is dependent on [this other one at ScenarioRunner](https://github.com/carla-simulator/scenario_runner/pull/858)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/106)
> Improved configuration parsing

- leaderboard/leaderboard_evaluator.py
Adds the hybrid mode to the LB, which affects the background activity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/108)
> Added hybrid mode

- leaderboard/autoagents/human_agent.py
Added side mirros to the human agent. These are optional and can be toggled on and off, but can very useful in some scenarios
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/116)
> Added side mirrors to the human agent

- leaderboard/scenarios/route_scenario.py
- leaderboard/utils/route_parser.py
Improved the night mode by only turning those close to the ego. Makes uses of the new _RouteLightsBehavior_ part of SR for the street lights, and the TM automatic lights system for the background activity vehicles
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/118)
> Improve night mode

- leaderboard/scenarios/route_scenario.py
Changed how the timeout works at routes. It now starts at a much lower value, but it icnreases every time the ego vehicle advanced through the route. This is done at the scenario runner repo, here we just call the new timeout behavior during the route's initialization
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/120)
> Improved timeout

- data/new_routes_training.xml
- leaderboard/autoagents/human_agent.py
- leaderboard/scenarios/route_scenario.py
- leaderboard/utils/statistics_manager.py
- scripts/route_creator.py
- scripts/scenario_creator.py
- scripts/weather_creator.py
Added the first batch of Leaderboard 2.0 training routes. These are meant to still be tested, as some scenarios are still missing / not fully tested yet.
Added two scripts to new criteria to the leaderboard statistics.
Added two new scripts `route_creator.py` and `weather_creator.py`, and improved the *scenario_creator.py*, all assets that help with the creation of the routes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/119)
> Leaderboard 2.0 training routes

- data/new_routes_training.xml
- leaderboard/scenarios/route_scenario.py
- scripts/route_creator.py
- scripts/route_displayer.py
- scripts/route_summarizer.py
- scripts/scenario_creator.py
Minor improvements to the route / scenario tools
New `route_summarizer.py`, to get a general overview of the route scenario configuration
Moved all show function to `route_displayer.py`. `route_creator.py` and `scenario_creator`.py will now be exclusively used to create.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/121)
> Improvements to scenario tools

- leaderboard/scenarios/scenario_manager.py
- leaderboard/utils/statistics_manager.py
Added the ego speed and control data to the live results file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/124)
> Added ego information to live results

- leaderboard/utils/statistics_manager.py
Live results will now also display the penalty value of each infraction
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/125)
> Added penalty info to live results

- data/new_routes_training.xml
- leaderboard/utils/result_writer.py
- scripts/route_creator.py
- scripts/route_displayer.py
Improved more LB 2.0 training routes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/128)
> More routes

- data/new_routes_training.xml
BlockedIntersection: 47
VehicleTurningRoute: 48
VehicleTurningRoutePedestrian: 44
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/129)
> Turning routes variation

- data/new_routes_training.xml
Triplicate training routes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/136)
> Triplicate training routes

- leaderboard/utils/route_indexer.py
Added a try catch to th resume for robustness in teh cloud
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/161)
> Fixed issue with resume

- leaderboard/autoagents/agent_wrapper.py
- leaderboard/autoagents/autonomous_agent.py
- leaderboard/autoagents/ros_base_agent.py
- leaderboard/utils/route_indexer.py
- leaderboard/utils/route_parser.py
- leaderboard/utils/statistics_manager.py
- run_leaderboard.sh
Added qualifier tracks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/170)
> Leaderboard 2.0 qualifier

- leaderboard/envs/sensor_interface.py
Fixed #165
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/173)
> Fixed issue with Speedometer

- leaderboard/autoagents/agent_wrapper.py
Fixes #175
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/carla-simulator/leaderboard/176)
> Fixed qualifier sensor limis
